### ISSUE TITLE
GUI for windows

### ISSUE THREAD

**Issue by ghost** [awused/aw-man#2]
A graphical user interface for windows, if possible.

**Comment by awused** [comment]
I'm not quite sure what you're asking for. It's already a gui image viewer, and it does work on windows though the steps to build it aren't ideal.

If you mean for something in place of editing the config file I'm not going to bother, it would be a lot of work to surface all the config options in a menu for little benefit. Many of the config options aren't expected to change while the program is running so there would be many knock-on effects. Setting up the configuration is something you really only need to do once.

**Comment by ghost** [comment]
What I meant was for an application/program.
Example - [CdisplayEx](https://www.cdisplayex.com/).

**Comment by awused** [comment]
That doesn't mean anything; this is already both an application and a program. I'm not sure what you think you're asking for, but I'm just going to close this.
